INSERT INTO EST_PROD_COMPRADOR_CPL (CD_CTR, CD_EMP, CD_PROD, DT_CAD)
VALUES (
    (SELECT CD_CTR FROM EST_PROD_COMPRADOR WHERE CD_EMP = 1 AND CD_COMPRADOR = codigoComprador),
    1,
    2,
    CONVERT (date, GETDATE())
);